name: Test Repository Secret

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository (optional, included for context)
    - name: Checkout code
      uses: actions/checkout@v4

    # Test the TEST_PUBLISH_PROFILE secret
    - name: Display TEST_PUBLISH_PROFILE Secret
      run: |
        if [ -n "${{ secrets.TEST_PUBLISH_PROFILE }}" ]; then
          echo "TEST_PUBLISH_PROFILE is set and accessible."
          echo "Secret value (masked): ${{ secrets.TEST_PUBLISH_PROFILE }}"
        else
          echo "TEST_PUBLISH_PROFILE is not set or empty."
          exit 1
        fi

